### ISSUE TITLE
SCHEMA_ONLY with ALIGNED, DISTCP and Partitions is too granular on partition distcp

### ISSUE THREAD

**Issue by dstreev** [cloudera-labs/hms-mirror#123]
Not resolving back up to table level directory.  So it's being redundant on distcp commands.
[2024-08-27_11-31-29.zip](https://github.com/user-attachments/files/16766106/2024-08-27_11-31-29.zip)

**Comment by dstreev** [comment]
Corrected Partition Level Calculations in distcp formulation.

**Comment by skeni-cld** [comment]
@dstreev  Is this issue taken care of in STORAGE_MIGRATION mode also?
