### ISSUE TITLE
Add support for Hive table backup in DISTCP mode

### ISSUE THREAD

**Issue by skeni-cld** [cloudera-labs/hms-mirror#152]
When we execute hms-mirror in DISTCP mode, it generate SQL which directly execute "alter table" statement on existing table to change location from "hdfs" to  ozone" for e.g.

ALTER TABLE table_name SET LOCATION "ofs://...";

We request a feature to provision for existing table backup  and  create  new table with same name pointing to ozone. Same process is seen SQL mode

Request to add below
1.   Backup existing table using "alter table rename to" statement
2. create a new table pointing to ozone with same name

**Comment by dstreev** [comment]
Added flag in Storage Migration called `createArchive`.  Valid only for STORAGE_MIGRATION when `distcp` is used.  Will work for NON-ACID tables.

ACID tables will require SQL to retain an archive.
