### ISSUE TITLE
extra character ; in LEFT_CleanUp_execute.sql is failing to clean up transfer tables

### ISSUE THREAD

**Issue by hpasumarthi** [cloudera-labs/hms-mirror#33]
Hello Team,
We have found that LEFT_CleanUp_execute.sql is being generate with special character in the following line 

-- To be run AFTER final RIGHT SQL statements.**;**

Which is causing the clean post script to fail with following message 

_2023-04-17 15:15:08,191 [pool-1-thread-3] INFO Cluster.runTableSql(484):LEFT:SQL:Post Migration Cleanup:-- To be run AFTER final RIGHT SQL statements.
2023-04-17 15:15:08,201 [pool-1-thread-3] ERROR Cluster.runTableSql(491):java.sql.SQLException: Error while compiling statement: FAILED: ParseException line 1:46 cannot recognize input near '<EOF>' '<EOF>' '<EOF>'_

![Screenshot 2023-04-17 at 18 56 35](https://user-images.githubusercontent.com/79252991/232570577-e35ec2df-ef15-4d41-b1a9-2d130499615d.png)

Can you please check the code and fix the left sql script. 

Hemanth

**Comment by hpasumarthi** [comment]
Hi @dstreev  we did managed to test this fix, looks like the issues still persist. 
can we test get this retested.

**Comment by dstreev** [comment]
Fixed issue where we didn't have a CR/LF in clean up script causing the script to miss the "USE <db>;" statement.
